name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Uses Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run:
          npm install -g yarn@1.17.2

      - name: Install dependencies
        run: yarn
      
      - name: bootstrap
        run: yarn run bootstrap

      - name: type-check
        run: yarn run tsc
